window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["cografya"] = window.KPSS_BANK["cografya"] || []).push(
{ id: "cog-tufan-037", konu: "Coğrafi Konum", soru: "Türkiye'nin Asya ile Avrupa arasında yer alması, İstanbul ve Çanakkale Boğazlarına sahip olması ve enerji kaynaklarına yakın bulunması, ülkenin hangi özelliğini artırır?", secenekler: ["Jeopolitik (stratejik) önemini", "Yüzölçümünü", "Ortalama yükseltisini", "Yıllık yağış miktarını", "Deprem riskini"], dogru: 0, aciklama: "Türkiye'nin iki kıta arasında, önemli deniz ve kara yolları ile enerji hatlarının kesiştiği yerde bulunması, jeopolitik (stratejik) önemini artırır. Bu konum, ülkeye siyasi, askeri ve ekonomik açıdan önemli avantajlar ve sorumluluklar yükler." },
{ id: "cog-tufan-038", konu: "Coğrafi Konum", soru: "Türkiye toprakları başlıca hangi iki kıta üzerinde yer alır?", secenekler: ["Asya - Afrika", "Asya - Avrupa", "Avrupa - Afrika", "Asya - Okyanusya", "Avrupa - Amerika"], dogru: 1, aciklama: "Türkiye'nin toprakları, Anadolu (Asya kıtası) ve Trakya (Avrupa kıtası) olmak üzere iki kıta üzerinde yer alır. Bu iki kıta İstanbul ve Çanakkale Boğazlarıyla birbirinden ayrılır; topraklarının büyük bölümü Asya'dadır." },
{ id: "cog-tufan-039", konu: "İklim ve Bitki Örtüsü", soru: "Kuzey Yarım Küre'de bir dağın güneye bakan yamaçlarının, kuzeye bakan yamaçlarından daha sıcak olmasının nedeni aşağıdakilerden hangisidir?", secenekler: ["Enlem", "Yükselti", "Bakı (yamaçların güneşe göre yönü)", "Denize uzaklık", "Rüzgârlar"], dogru: 2, aciklama: "Bakı, bir yamacın güneş ışınlarına göre yönüdür. Kuzey Yarım Küre'de güneye bakan yamaçlar güneş ışınlarını daha dik açıyla aldığından daha sıcak, daha aydınlık ve daha az kar tutan yamaçlardır. Bu, aynı dağın iki yamacı arasında sıcaklık farkı oluşturur." },
{ id: "cog-tufan-040", konu: "İklim ve Bitki Örtüsü", soru: "Türkiye'de yıllık yağış miktarının en fazla olduğu yöre aşağıdakilerden hangisidir?", secenekler: ["Konya çevresi", "İç Anadolu'nun ortası", "Güneydoğu Anadolu", "Doğu Karadeniz kıyıları", "Tuz Gölü çevresi"], dogru: 3, aciklama: "Doğu Karadeniz kıyıları (özellikle Rize çevresi), dağların kıyıya paralel uzanması ve denizden gelen nemli havanın yamaçlarda yükselmesi nedeniyle Türkiye'nin en fazla yağış alan yöresidir. En az yağışı ise İç Anadolu (Tuz Gölü, Konya çevresi) alır." },
{ id: "cog-tufan-041", konu: "İklim ve Bitki Örtüsü", soru: "Yazları sıcak ve kurak, kışları ılık ve yağışlı geçen; doğal bitki örtüsü maki olan iklim tipi aşağıdakilerden hangisidir?", secenekler: ["Karasal iklim", "Karadeniz iklimi", "Ekvatoral iklim", "Tundra iklimi", "Akdeniz iklimi"], dogru: 4, aciklama: "Akdeniz iklimi; yazları sıcak ve kurak, kışları ılık ve yağışlı geçer. Doğal bitki örtüsü, kuraklığa dayanıklı kısa boylu çalılardan oluşan makidir. Türkiye'de Akdeniz ve Ege kıyıları ile Marmara'nın güneyinde etkilidir." },
{ id: "cog-tufan-042", konu: "Yer Şekilleri", soru: "Türkiye'nin güneyinde, Akdeniz kıyısına genel olarak paralel uzanan en uzun sıradağı aşağıdakilerden hangisidir?", secenekler: ["Toros Dağları", "Küre Dağları", "Yıldız Dağları", "Menteşe Dağları", "Nur Dağları"], dogru: 0, aciklama: "Toros Dağları, Türkiye'nin güneyinde Akdeniz kıyısı boyunca uzanan en uzun sıradağdır. Kıyıya paralel uzanması, kıyı ile iç kesim arasında iklim ve ulaşım farklarına yol açar; karstik yer şekilleri bakımından da zengindir." },
{ id: "cog-tufan-043", konu: "Yer Şekilleri", soru: "Aşağıdaki dağlardan hangisi volkanik kökenli bir dağ değildir?", secenekler: ["Erciyes Dağı", "Kaçkar Dağı", "Nemrut Dağı", "Süphan Dağı", "Ağrı Dağı"], dogru: 1, aciklama: "Erciyes, Nemrut, Süphan ve Ağrı volkanik püskürmelerle oluşmuş volkanik dağlardır. Kaçkar Dağı ise Doğu Karadeniz'de yer alan bir kıvrım dağıdır; volkanik değildir. Bu yüzden farklı olan Kaçkar Dağı'dır." },
{ id: "cog-tufan-044", konu: "Yer Şekilleri", soru: "Suları denize ulaşamayan, kapalı havza özelliği gösteren ve karstik yapısıyla bilinen ovamız aşağıdakilerden hangisidir?", secenekler: ["Çukurova", "Bafra Ovası", "Konya Ovası", "Çarşamba Ovası", "Adapazarı Ovası"], dogru: 2, aciklama: "Konya Ovası, suları denize ulaşamayan bir kapalı havzadır; yağışın az, buharlaşmanın fazla olması ve karstik yapı nedeniyle yer yer obruklar görülür. Çukurova, Bafra ve Çarşamba ise akarsuların denize döküldüğü delta ovalarıdır." },
{ id: "cog-tufan-045", konu: "Nüfus ve Yerleşme", soru: "Bir bölgedeki toplam nüfusun, o bölgenin yüzölçümüne bölünmesiyle bulunan değere ne ad verilir?", secenekler: ["Doğal nüfus artışı", "Tarımsal nüfus yoğunluğu", "Fizyolojik nüfus yoğunluğu", "Aritmetik nüfus yoğunluğu", "Nüfus piramidi"], dogru: 3, aciklama: "Aritmetik nüfus yoğunluğu, bir yerdeki toplam nüfusun o yerin yüzölçümüne (km²) bölünmesiyle bulunur ve kilometrekareye düşen kişi sayısını gösterir. Tarımsal ve fizyolojik yoğunluk ise nüfusu tarım alanına ya da ekili-dikili alana oranlayan farklı ölçütlerdir." },
{ id: "cog-tufan-046", konu: "Nüfus ve Yerleşme", soru: "Türkiye'de sanayileşme ve kırdan kente göçün bir sonucu olarak zamanla sürekli artan olgu aşağıdakilerden hangisidir?", secenekler: ["Kırsal nüfus oranı", "Tarımla uğraşanların oranı", "Ortalama hane halkı büyüklüğü", "Kaba doğum oranı", "Şehirli nüfus oranı (şehirleşme)"], dogru: 4, aciklama: "Sanayileşme ve kırdan kente göç sonucunda şehirlerde yaşayan nüfusun toplam nüfusa oranı, yani şehirleşme oranı sürekli artmıştır. Buna karşılık kırsal nüfusun ve tarımla uğraşanların oranı zamanla azalmıştır." },
{ id: "cog-tufan-047", konu: "Tarım ve Hayvancılık", soru: "Aşağıdaki tarım ürünlerinden hangisi özellikle Çukurova, Ege ovaları ve Güneydoğu Anadolu (GAP) bölgesinde yaygın olarak yetiştirilir?", secenekler: ["Pamuk", "Çay", "Fındık", "Muz", "Şeker pancarı"], dogru: 0, aciklama: "Pamuk; sıcaklık ve sulama isteği yüksek bir üründür, bu nedenle Çukurova, Ege ovaları ve GAP ile sulanan Güneydoğu Anadolu'da yaygın olarak yetiştirilir. Tekstil sanayisinin temel ham maddesidir." },
{ id: "cog-tufan-048", konu: "Tarım ve Hayvancılık", soru: "Kışları ılık geçen Ege ve Akdeniz kıyılarında yaygın olarak yetiştirilen ve yağı çıkarılarak da değerlendirilen ürün aşağıdakilerden hangisidir?", secenekler: ["Çay", "Zeytin", "Fındık", "Şeker pancarı", "Patates"], dogru: 1, aciklama: "Zeytin, kışları ılık geçen yerlerde yetişebilen bir Akdeniz bitkisidir; bu nedenle Ege ve Akdeniz kıyılarında yaygındır. Sofralık olarak tüketildiği gibi zeytinyağı üretiminde de kullanılır. Don olayına duyarlı olduğu için iç bölgelerde yetişmez." },
{ id: "cog-tufan-049", konu: "Madenler, Enerji ve Sanayi", soru: "Türkiye'nin dünyada önemli üreticilerinden olduğu; paslanmaz çelik yapımında kullanılan ve Elazığ (Guleman) çevresinde çıkarılan maden aşağıdakilerden hangisidir?", secenekler: ["Bor", "Bakır", "Krom", "Linyit", "Boksit"], dogru: 2, aciklama: "Krom, paslanmaz çelik ve alaşım yapımında kullanılan bir madendir; Türkiye dünyada önemli krom üreticilerinden biridir ve Elazığ (Guleman) çevresi başlıca çıkarım alanıdır. Bor ise cam-seramikte kullanılır ve Türkiye rezervde dünya lideridir." },
{ id: "cog-tufan-050", konu: "Madenler, Enerji ve Sanayi", soru: "Aşağıdaki illerden hangisi Türkiye'de demir-çelik sanayisiyle özdeşleşmiş merkezlerden biri DEĞİLDİR?", secenekler: ["Karabük", "Ereğli (Zonguldak)", "İskenderun", "Rize", "Kırıkkale"], dogru: 3, aciklama: "Türkiye'de demir-çelik sanayisi Karabük, Ereğli ve İskenderun'da yoğunlaşmıştır; bu merkezler kömür ve demir kaynaklarına ya da limanlara yakınlığıyla öne çıkar. Rize ise demir-çelik ile değil, çay üretimiyle özdeşleşmiştir; bu yüzden farklı olan Rize'dir." },
{ id: "cog-tufan-051", konu: "Ulaşım, Ticaret ve Turizm", soru: "İstanbul ve Çanakkale Boğazları, Türkiye'ye özellikle aşağıdakilerden hangisi bakımından avantaj sağlar?", secenekler: ["Tarım alanlarının genişliği", "Maden yataklarının zenginliği", "Orman varlığının fazlalığı", "Akarsu enerjisi potansiyeli", "Deniz ulaşımı ve stratejik geçiş kontrolü"], dogru: 4, aciklama: "İstanbul ve Çanakkale Boğazları, Karadeniz'i Akdeniz'e bağlayan tek deniz yoludur; bu nedenle deniz ulaşımı ve uluslararası geçişlerin kontrolü bakımından Türkiye'ye büyük stratejik avantaj sağlar. Boğazların yönetimi Montrö Sözleşmesi ile Türkiye'ye aittir." },
{ id: "cog-tufan-052", konu: "Ulaşım, Ticaret ve Turizm", soru: "Günümüzde Türkiye'nin ihracatının büyük bölümünü aşağıdakilerden hangisi oluşturur?", secenekler: ["Sanayi ürünleri", "Ham petrol", "Doğal gaz", "Taş kömürü", "Değerli metaller"], dogru: 0, aciklama: "Türkiye'nin ihracatının büyük bölümünü otomotiv, tekstil, makine ve gıda gibi sanayi (işlenmiş) ürünleri oluşturur. Petrol ve doğal gaz gibi enerji kaynakları ise büyük ölçüde ithal edildiğinden ihracat kalemi değil, ithalatta önemli bir yük oluşturur." },
{ id: "cog-tufan-053", konu: "Bölgeler ve Projeler", soru: "Türkiye'de engebeli yüzey şekilleri, karasal iklimi ve sınırlı iş olanakları nedeniyle dışarıya en çok göç veren bölgelerimizden biri aşağıdakilerden hangisidir?", secenekler: ["Marmara Bölgesi", "Doğu Anadolu Bölgesi", "Ege Bölgesi", "Akdeniz Bölgesi", "İç Anadolu Bölgesi"], dogru: 1, aciklama: "Doğu Anadolu Bölgesi; yüksek ve engebeli yapısı, sert karasal iklimi ve sanayinin yeterince gelişmemiş olması nedeniyle iş olanaklarının sınırlı olduğu, bu yüzden dışarıya en çok göç veren bölgelerimizdendir. Marmara ise sanayi ve iş olanakları sayesinde en çok göç alan bölgedir." },
{ id: "cog-tufan-054", konu: "Bölgeler ve Projeler", soru: "Türkiye'de sanayi kuruluşlarının en yoğun olarak toplandığı bölge aşağıdakilerden hangisidir?", secenekler: ["Doğu Anadolu Bölgesi", "Güneydoğu Anadolu Bölgesi", "Karadeniz Bölgesi", "Marmara Bölgesi", "İç Anadolu Bölgesi"], dogru: 3, aciklama: "Marmara Bölgesi; ulaşım kolaylığı, limanları, geniş iç pazarı ve nitelikli iş gücü sayesinde Türkiye'de sanayinin en yoğun olduğu bölgedir (İstanbul, Kocaeli, Bursa gibi merkezler). Bu durum bölgeye yoğun göç çekilmesine de yol açmıştır." }
);
