window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["cografya"] = window.KPSS_BANK["cografya"] || []).push(
{ id: "cog-tufan-019", konu: "Coğrafi Konum", soru: "Türkiye'nin üç tarafının denizlerle çevrili olması, Asya ile Avrupa arasında bir köprü konumunda bulunması ve dağlarının uzanış yönü gibi özellikleri hangi konumuyla ilgilidir?", secenekler: ["Özel konumu", "Matematik konumu", "Enlem konumu", "Boylam konumu", "Mutlak konumu"], dogru: 0, aciklama: "Özel konum, bir yerin denizlere, kıtalara, komşularına ve yer şekillerine göre konumudur; Türkiye'nin üç tarafının denizlerle çevrili olması ve iki kıta arasında yer alması özel konumuyla ilgilidir. Matematik konum ise bir yerin enlem ve boylam değerleriyle (mutlak konumuyla) ifade edilir." },
{ id: "cog-tufan-020", konu: "Coğrafi Konum", soru: "Türkiye'de güneyden kuzeye doğru gidildikçe sıcaklık ortalamalarının genel olarak azalması aşağıdaki faktörlerden hangisiyle açıklanır?", secenekler: ["Yükselti", "Enlem", "Karasallık", "Denize göre konum", "Bakı"], dogru: 1, aciklama: "Enlem, bir yerin Ekvator'a olan uzaklığıdır ve sıcaklığı belirleyen en temel faktördür. Ekvator'dan kutuplara (güneyden kuzeye) gidildikçe güneş ışınları daha eğik geldiği için sıcaklık azalır. Yükselti ve karasallık da sıcaklığı etkiler ama kuzey-güney yönündeki genel azalışın nedeni enlemdir." },
{ id: "cog-tufan-021", konu: "İklim ve Bitki Örtüsü", soru: "İç Anadolu'da görülen; yazları sıcak ve kurak, kışları soğuk ve kar yağışlı olan, gece ile gündüz ve yaz ile kış arasındaki sıcaklık farkının fazla olduğu iklim tipi aşağıdakilerden hangisidir?", secenekler: ["Akdeniz iklimi", "Karadeniz iklimi", "Karasal iklim", "Marmara (geçiş) iklimi", "Ekvatoral iklim"], dogru: 2, aciklama: "Karasal iklim, denizin ılımanlaştırıcı etkisinden uzak iç bölgelerde görülür; yaz-kış ve gece-gündüz arasındaki sıcaklık farkı fazladır. Doğal bitki örtüsü bozkırdır (step). İç Anadolu, Doğu Anadolu ve İç Batı Anadolu'da bu iklim etkilidir." },
{ id: "cog-tufan-022", konu: "İklim ve Bitki Örtüsü", soru: "Türkiye'de yıllık yağış miktarının en az olduğu bölge aşağıdakilerden hangisidir?", secenekler: ["Karadeniz Bölgesi", "Marmara Bölgesi", "Akdeniz Bölgesi", "İç Anadolu Bölgesi", "Ege Bölgesi"], dogru: 3, aciklama: "İç Anadolu Bölgesi, çevresinin dağlarla çevrili olması nedeniyle denizlerin nemli havasından yeterince yararlanamaz; bu yüzden Türkiye'de en az yağış alan bölgedir (özellikle Tuz Gölü ve Konya çevresi). En fazla yağışı ise Doğu Karadeniz kıyıları alır." },
{ id: "cog-tufan-023", konu: "İklim ve Bitki Örtüsü", soru: "Aynı enlemde bulunan iki yerden yüksekte olanın sıcaklığının daha düşük olması aşağıdaki faktörlerden hangisiyle açıklanır?", secenekler: ["Enlem", "Denize uzaklık", "Bakı", "Rüzgârlar", "Yükselti"], dogru: 4, aciklama: "Yükselti arttıkça sıcaklık düşer; genel olarak her 200 metre yükselmede sıcaklık ortalama 1 °C azalır. Bunun nedeni, atmosferin yerden yükseldikçe seyrelmesi ve ısıyı daha az tutmasıdır. Enlemleri aynı olan iki yer arasındaki sıcaklık farkı bu örnekte yükseltiden kaynaklanır." },
{ id: "cog-tufan-024", konu: "Yer Şekilleri", soru: "Türkiye'nin yüzölçümü bakımından en büyük gölü aşağıdakilerden hangisidir?", secenekler: ["Van Gölü", "Tuz Gölü", "Beyşehir Gölü", "Eğirdir Gölü", "İznik Gölü"], dogru: 0, aciklama: "Van Gölü, Türkiye'nin yüzölçümü en büyük gölüdür; suları sodalıdır ve volkanik faaliyet sonucu Nemrut Dağı'nın lavlarının bir vadinin önünü kapatmasıyla oluşmuş bir set gölüdür. Tuz Gölü ise yüzölçümü bakımından ikinci sıradadır ve tuz üretimiyle önemlidir." },
{ id: "cog-tufan-025", konu: "Yer Şekilleri", soru: "Türkiye'nin kuzeyinde doğu-batı doğrultusunda uzanan ve ülkedeki yıkıcı depremlerin büyük bölümünün kaynağı olan fay hattı aşağıdakilerden hangisidir?", secenekler: ["Doğu Anadolu Fay Hattı", "Kuzey Anadolu Fay Hattı", "Batı Anadolu Fay Hattı", "Ege grabenleri", "Toros Fay Hattı"], dogru: 1, aciklama: "Kuzey Anadolu Fay Hattı (KAF), Türkiye'nin kuzeyinde doğu-batı yönünde uzanır ve tarih boyunca birçok büyük depreme yol açmıştır. Türkiye, Alp-Himalaya deprem kuşağında yer aldığı için deprem riski yüksektir. Doğu Anadolu Fay Hattı ise ülkenin güneydoğusunda etkilidir." },
{ id: "cog-tufan-026", konu: "Yer Şekilleri", soru: "Ege kıyılarının çok girintili çıkıntılı (koy, körfez ve yarımadalarca zengin) olmasının temel nedeni aşağıdakilerden hangisidir?", secenekler: ["Kıyı boyunca akıntıların bulunması", "Yağış miktarının fazla olması", "Dağların kıyıya dik (enine) uzanması", "Yükseltinin az olması", "Denizin sığ olması"], dogru: 2, aciklama: "Ege Bölgesi'nde dağlar kıyıya dik (enine) uzandığı için deniz, dağlar arasındaki çöküntü ovalarına sokulur; böylece çok sayıda koy, körfez ve yarımada oluşur. Karadeniz ve Akdeniz'de ise dağlar kıyıya paralel uzandığından kıyılar az girintilidir." },
{ id: "cog-tufan-027", konu: "Nüfus ve Yerleşme", soru: "Türkiye'de nüfus yoğunluğunun en fazla olduğu bölge aşağıdakilerden hangisidir?", secenekler: ["Doğu Anadolu Bölgesi", "Güneydoğu Anadolu Bölgesi", "İç Anadolu Bölgesi", "Marmara Bölgesi", "Karadeniz Bölgesi"], dogru: 3, aciklama: "Marmara Bölgesi; sanayi, ticaret ve ulaşımın gelişmiş olması, iklimin elverişliliği ve İstanbul'un varlığı nedeniyle Türkiye'de nüfus yoğunluğu en fazla olan bölgedir. Doğu Anadolu ise yüksek ve engebeli yapısı ile karasal iklimi nedeniyle en seyrek nüfuslu bölgedir." },
{ id: "cog-tufan-028", konu: "Nüfus ve Yerleşme", soru: "Bir ülkenin nüfus piramidinin tabanının geniş olması, o ülke için aşağıdakilerden hangisini gösterir?", secenekler: ["Yaşlı nüfusun fazla olduğunu", "Toplam nüfusun azaldığını", "Ortalama yaşam süresinin çok uzun olduğunu", "Kadın nüfusun erkek nüfustan çok fazla olduğunu", "Genç (çocuk) nüfusun fazla olduğunu"], dogru: 4, aciklama: "Nüfus piramidinin tabanının geniş olması, doğum oranının yüksek ve genç (çocuk) nüfusun fazla olduğunu gösterir; bu, gelişmekte olan ülkelerin bir özelliğidir. Tabanı dar, tepesi geniş piramitler ise yaşlı nüfusun arttığı gelişmiş ülkeleri işaret eder." },
{ id: "cog-tufan-029", konu: "Tarım ve Hayvancılık", soru: "Türkiye'de en fazla ekim alanına sahip olan ve özellikle İç Anadolu'da yaygın olarak yetiştirilen tahıl aşağıdakilerden hangisidir?", secenekler: ["Buğday", "Çeltik (pirinç)", "Mısır", "Çay", "Muz"], dogru: 0, aciklama: "Buğday, karasal iklimin yağış rejimine uyum sağladığı için Türkiye'de en geniş ekim alanına sahip tahıldır; İç Anadolu bu nedenle 'Türkiye'nin tahıl ambarı' olarak anılır. Çeltik bol su, çay ve muz ise nemli-ılıman iklim istediğinden farklı bölgelerde yetişir." },
{ id: "cog-tufan-030", konu: "Tarım ve Hayvancılık", soru: "Üretiminin büyük bölümü Doğu Karadeniz kıyılarında (Giresun, Ordu çevresinde) yapılan ve Türkiye'nin dünya üretiminde ilk sırada yer aldığı tarım ürünü aşağıdakilerden hangisidir?", secenekler: ["Pamuk", "Fındık", "Zeytin", "Ayçiçeği", "Şeker pancarı"], dogru: 1, aciklama: "Fındık, nemli ve ılıman iklim ister; bu koşulların bulunduğu Doğu Karadeniz kıyılarında yoğun olarak yetiştirilir ve Türkiye dünya fındık üretiminde birinci sıradadır. Pamuk Çukurova ve Ege'de, zeytin ise Ege ve Akdeniz kıyılarında yaygındır." },
{ id: "cog-tufan-031", konu: "Madenler, Enerji ve Sanayi", soru: "Türkiye'de taş kömürünün çıkarıldığı ve demir-çelik sanayisiyle özdeşleşmiş olan ilimiz aşağıdakilerden hangisidir?", secenekler: ["Soma", "Elbistan", "Zonguldak", "Divriği", "Seydişehir"], dogru: 2, aciklama: "Zonguldak, Türkiye'nin en önemli taş kömürü havzasıdır ve yakınındaki Ereğli ile Karabük demir-çelik tesislerine kaynaklık eder. Soma ve Elbistan linyit (daha düşük kalorili kömür) çıkarılan yerlerdir; Divriği demir, Seydişehir ise alüminyum (boksit) ile öne çıkar." },
{ id: "cog-tufan-032", konu: "Madenler, Enerji ve Sanayi", soru: "Akarsular üzerine kurulan barajlarda suyun gücünden yararlanılarak elektrik üretilmesine dayanan ve Türkiye'nin en çok yararlandığı yenilenebilir enerji türü aşağıdakilerden hangisidir?", secenekler: ["Rüzgâr enerjisi", "Güneş enerjisi", "Jeotermal enerji", "Hidroelektrik enerji", "Biyokütle enerjisi"], dogru: 3, aciklama: "Hidroelektrik enerji, akarsuların üzerine kurulan barajlarda suyun potansiyel enerjisinden elektrik üretilmesidir; Türkiye engebeli yapısı ve akarsu potansiyeli sayesinde bu kaynaktan geniş ölçüde yararlanır (Atatürk, Keban, Karakaya barajları gibi). Yenilenebilir olması ve dışa bağımlılığı azaltması önemli avantajlarıdır." },
{ id: "cog-tufan-033", konu: "Ulaşım, Ticaret ve Turizm", soru: "Türkiye'de yük ve yolcu taşımacılığında en fazla paya sahip olan ulaşım türü aşağıdakilerden hangisidir?", secenekler: ["Denizyolu", "Havayolu", "Demiryolu", "Boru hattı", "Karayolu"], dogru: 4, aciklama: "Karayolu, kapıdan kapıya taşıma esnekliği ve yaygın ağı sayesinde Türkiye'de yük ve yolcu taşımacılığında en büyük paya sahiptir. Ancak maliyet ve çevre açısından daha ekonomik olan demiryolu ve denizyolu taşımacılığının payını artırmaya yönelik çalışmalar yapılmaktadır." },
{ id: "cog-tufan-034", konu: "Ulaşım, Ticaret ve Turizm", soru: "Peribacaları, yer altı şehirleri ve sıcak hava balonu turlarıyla ünlü, UNESCO Dünya Mirası Listesi'nde yer alan turizm yöremiz aşağıdakilerden hangisidir?", secenekler: ["Kapadokya", "Pamukkale", "Efes", "Nemrut", "Truva"], dogru: 0, aciklama: "Kapadokya (Nevşehir ve çevresi), volkanik tüf tabakalarının aşınmasıyla oluşan peribacaları, kayaya oyulmuş yer altı şehirleri ve balon turlarıyla ünlü bir kültür turizmi merkezidir. Pamukkale travertenleriyle, Efes ise antik kentiyle öne çıkar; hepsi farklı turizm değerleridir." },
{ id: "cog-tufan-035", konu: "Bölgeler ve Projeler", soru: "Türkiye'de kırsal alanlardan kentlere doğru yaşanan iç göçün en temel nedeni aşağıdakilerden hangisidir?", secenekler: ["Kentlerde iklimin daha uygun olması", "Kentlerde iş, eğitim ve sağlık olanaklarının daha fazla olması", "Kırsal alanlarda nüfusun az olması", "Kentlerde tarımın daha gelişmiş olması", "Kırsalda ulaşımın daha kolay olması"], dogru: 1, aciklama: "Kırdan kente göçün temel nedeni, kentlerdeki iş, eğitim ve sağlık olanaklarının kırsala göre daha fazla olması (çekici nedenler) ve kırsalda tarımda makineleşmeyle iş gücüne olan ihtiyacın azalmasıdır (itici nedenler). Bu göç, büyük kentlerde çarpık kentleşme ve altyapı sorunlarına yol açar." },
{ id: "cog-tufan-036", konu: "Bölgeler ve Projeler", soru: "Türkiye'de nüfusu en fazla olan il aşağıdakilerden hangisidir?", secenekler: ["Ankara", "İzmir", "Bursa", "İstanbul", "Antalya"], dogru: 3, aciklama: "İstanbul, sanayi, ticaret, ulaşım ve hizmet sektörlerinin yoğunlaştığı bir merkez olması nedeniyle Türkiye'nin nüfusu en fazla olan ilidir ve en çok göç alan ildir. Ankara nüfus bakımından ikinci sıradadır; başkent olması nedeniyle idari bir merkezdir." }
);
