window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["guncel"] = window.KPSS_BANK["guncel"] || []).push(
{ id: "gun-tufan-013", konu: "Spor", soru: "2025 Avrupa Basketbol Şampiyonası'nda (EuroBasket) Türkiye A Milli Erkek Takımı finale yükselmiş, ancak finalde yenilerek ikinci (gümüş madalya) olmuştur. Türkiye'yi finalde yenerek şampiyon olan ülke aşağıdakilerden hangisidir?", secenekler: ["Almanya", "Yunanistan", "Fransa", "Sırbistan", "İspanya"], dogru: 0, aciklama: "EuroBasket 2025'te Türkiye A Milli Erkek Basketbol Takımı finale yükselmiş; yarı finalde Yunanistan'ı yenmesine karşın finalde Almanya'ya yenilerek ikinci olmuş ve gümüş madalya kazanmıştır. Almanya ise uzun bir aranın ardından Avrupa şampiyonu olmuştur." },
{ id: "gun-tufan-014", konu: "Türkiye Gündemi", soru: "2025 Kadın Voleybol Dünya Şampiyonası'nda Türkiye A Milli Kadın Voleybol Takımı, finalde İtalya'ya yenilerek kaçıncı olmuştur?", secenekler: ["Birinci", "İkinci", "Üçüncü", "Dördüncü", "Beşinci"], dogru: 1, aciklama: "Türkiye A Milli Kadın Voleybol Takımı, 2025 Dünya Şampiyonası'nda finale yükselmiş ve finalde İtalya'ya yenilerek dünya ikincisi olmuştur. Bu derece, takımın Dünya Şampiyonası tarihindeki en iyi sonucudur ve organizasyonda ilk kez madalya kazanılmıştır." },
{ id: "gun-tufan-015", konu: "Bilim ve Teknoloji", soru: "Türkiye'nin ikinci astronotu olarak, Türk Uzay Bilim Misyonu kapsamında yörünge altı araştırma uçuşunu gerçekleştiren kişi aşağıdakilerden hangisidir?", secenekler: ["Alper Gezeravcı", "Selçuk Bayraktar", "Tuva Cihangir Atasever", "Aziz Sancar", "Uğur Şahin"], dogru: 2, aciklama: "Türkiye'nin uzaya giden ilk astronotu Alper Gezeravcı (Uluslararası Uzay İstasyonu görevi), ikinci astronotu ise Tuva Cihangir Atasever'dir. Atasever, Türk Uzay Bilim Misyonu kapsamında yörünge altı bir araştırma uçuşu gerçekleştirmiştir; bu görevler Milli Uzay Programı'nın parçasıdır." },
{ id: "gun-tufan-016", konu: "Kültür-Sanat", soru: "2025 Cannes Film Festivali'nde en büyük ödül olan Altın Palmiye'yi kazanan yönetmen aşağıdakilerden hangisidir?", secenekler: ["Sean Baker", "Christopher Nolan", "Nuri Bilge Ceylan", "Jafar Panahi", "Bong Joon-ho"], dogru: 3, aciklama: "2025 Cannes Film Festivali'nde Altın Palmiye, İranlı yönetmen Jafar Panahi'nin 'It Was Just an Accident' (Yalnızca Bir Kaza) adlı filmine verilmiştir. Altın Palmiye, Cannes Film Festivali'nin en prestijli ödülüdür." },
{ id: "gun-tufan-017", konu: "Ödüller", soru: "2025 Nobel Ekonomi Ödülü, aşağıdaki alanların hangisindeki çalışmalara verilmiştir?", secenekler: ["Enflasyonla mücadele politikaları", "Uluslararası ticaret anlaşmaları", "Yoksullukla mücadele deneyleri", "Davranışsal ekonomi", "Yenilik (inovasyon) odaklı ekonomik büyüme"], dogru: 4, aciklama: "2025 Nobel Ekonomi Ödülü, teknolojik yenilik yoluyla sürdürülebilir ekonomik büyümenin nasıl sağlandığını açıklayan çalışmalara (Joel Mokyr, Philippe Aghion ve Peter Howitt) verilmiştir. 'Yaratıcı yıkım' kavramı, eski teknolojilerin yerini yenilerinin almasıyla büyümenin sürmesini anlatan bu teorinin merkezindedir." },
{ id: "gun-tufan-018", konu: "Bilim ve Teknoloji", soru: "2025 Nobel Fizyoloji veya Tıp Ödülü, aşağıdaki alanların hangisindeki keşiflere verilmiştir?", secenekler: ["Periferik bağışıklık toleransı", "Kanser aşısının geliştirilmesi", "İnsan beyninin haritalanması", "Gen terapisi yöntemleri", "Organ nakli teknikleri"], dogru: 0, aciklama: "2025 Nobel Tıp Ödülü, bağışıklık sisteminin vücudun kendi dokularına zarar vermesini önleyen 'periferik bağışıklık toleransı' mekanizmasının keşfine (Mary Brunkow, Fred Ramsdell ve Shimon Sakaguchi) verilmiştir. Bu keşif, otoimmün hastalıkların anlaşılması açısından büyük önem taşır." }
);
