window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["guncel"] = window.KPSS_BANK["guncel"] || []).push(
{ id: "gun-tufan-001", konu: "Uluslararası Gündem", soru: "2025 Nobel Barış Ödülü, ülkesinde demokratik haklar ve diktatörlükten barışçıl geçiş için yürüttüğü mücadeleyle tanınan hangi Venezuelalı muhalefet liderine verilmiştir?", secenekler: ["María Corina Machado", "Juan Guaidó", "Nicolás Maduro", "Svetlana Tihanovskaya", "Denis Mukwege"], dogru: 0, aciklama: "2025 Nobel Barış Ödülü, Venezuela'da demokratik hakları savunması ve barışçıl siyasi geçiş için verdiği mücadele nedeniyle muhalefet lideri María Corina Machado'ya verilmiştir. Nicolás Maduro ülkenin devlet başkanıdır; ödülü kazanan kişi değildir. Nobel Barış Ödülü, uluslararası barışa ve insan haklarına katkı sunanlara verilir." },
{ id: "gun-tufan-002", konu: "Türkiye Gündemi", soru: "Türkiye'nin havacılık, uzay ve teknoloji festivali TEKNOFEST'in 2026 yılında düzenleneceği il aşağıdakilerden hangisidir?", secenekler: ["İstanbul", "İzmir", "Şanlıurfa", "Ankara", "Adana"], dogru: 2, aciklama: "TEKNOFEST 2026'nın, köklü tarihi ve medeniyet mirasıyla öne çıkan Şanlıurfa'da düzenleneceği açıklanmıştır (30 Eylül - 4 Ekim 2026). TEKNOFEST, gençleri teknoloji ve millî teknoloji hamlesi çevresinde yarıştıran, her yıl farklı bir şehirde yapılan bir festivaldir." },
{ id: "gun-tufan-003", konu: "Bilim ve Teknoloji", soru: "Türkiye'nin yerli ve millî imkânlarla geliştirilen ilk haberleşme uydusu aşağıdakilerden hangisidir?", secenekler: ["İMECE", "GÖKTÜRK-1", "RASAT", "BİLSAT", "TÜRKSAT 6A"], dogru: 4, aciklama: "TÜRKSAT 6A, Türkiye'nin yerli ve millî imkânlarla üretilen ilk haberleşme uydusudur ve uzaya fırlatılarak Türkiye'yi kendi haberleşme uydusunu üreten ülkeler arasına sokmuştur. İMECE bir yer gözlem uydusu, RASAT ve BİLSAT ise daha önceki gözlem uydularıdır; haberleşme değil gözlem amaçlıdır." },
{ id: "gun-tufan-004", konu: "Spor", soru: "2025 Formula 1 Dünya Şampiyonluğunu kazanarak kariyerinin ilk şampiyonluğuna ulaşan ve Max Verstappen'in üst üste süren şampiyonluk serisini sona erdiren pilot aşağıdakilerden hangisidir?", secenekler: ["Max Verstappen", "Lando Norris", "Oscar Piastri", "Charles Leclerc", "Lewis Hamilton"], dogru: 1, aciklama: "2025 Formula 1 Dünya Şampiyonu, McLaren pilotu Lando Norris olmuştur; bu, Norris'in ilk dünya şampiyonluğudur ve Max Verstappen'in dört yıl süren şampiyonluk dönemini sona erdirmiştir. Verstappen önceki yılların şampiyonuydu; 2025'te unvanı Norris'e kaptırmıştır." },
{ id: "gun-tufan-005", konu: "Kültür-Sanat", soru: "2025 Eurovision Şarkı Yarışması'nı 'Wasted Love' adlı şarkısıyla kazanan ülke aşağıdakilerden hangisidir?", secenekler: ["İsveç", "İsrail", "Avusturya", "İsviçre", "İtalya"], dogru: 2, aciklama: "2025 Eurovision Şarkı Yarışması'nı, sanatçı JJ'in seslendirdiği 'Wasted Love' şarkısıyla Avusturya kazanmıştır; bu, Avusturya'nın üçüncü Eurovision birinciliğidir. Yarışmanın finali İsviçre'nin Basel kentinde düzenlenmiştir; ancak ev sahibi ülke ile kazanan ülke farklıdır." },
{ id: "gun-tufan-006", konu: "Ödüller", soru: "2025'te düzenlenen 97. Akademi Ödülleri'nde (Oscar) En İyi Film ödülünü kazanan yapım aşağıdakilerden hangisidir?", secenekler: ["Conclave", "The Brutalist", "Emilia Pérez", "Anora", "Wicked"], dogru: 3, aciklama: "97. Akademi Ödülleri'nde (2 Mart 2025) En İyi Film ödülünü, yönetmenliğini Sean Baker'ın yaptığı 'Anora' kazanmıştır; film ayrıca En İyi Yönetmen ve En İyi Kadın Oyuncu (Mikey Madison) dâhil beş Oscar almıştır. Diğer seçenekler aynı törende aday olan ama En İyi Film ödülünü kazanamayan yapımlardır." }
);
