window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["guncel"] = window.KPSS_BANK["guncel"] || []).push(
{ id: "gun-tufan-007", konu: "Uluslararası Gündem", soru: "2024 Yaz Olimpiyat Oyunları hangi şehirde düzenlenmiştir?", secenekler: ["Paris", "Tokyo", "Los Angeles", "Londra", "Rio de Janeiro"], dogru: 0, aciklama: "2024 Yaz Olimpiyat Oyunları Fransa'nın başkenti Paris'te düzenlenmiştir. Paris, olimpiyatlara üçüncü kez ev sahipliği yapan şehir olmuştur. Bir sonraki yaz olimpiyatları 2028'de Los Angeles'ta yapılacaktır." },
{ id: "gun-tufan-008", konu: "Türkiye Gündemi", soru: "2025 yılında UNESCO Dünya Mirası Listesi'ne eklenerek Türkiye'nin bu listedeki alan sayısını 22'ye çıkaran; tarihte ilk madeni paranın basıldığı yer olarak bilinen antik kent aşağıdakilerden hangisidir?", secenekler: ["Efes", "Sardes (Sart) Antik Kenti", "Truva", "Bergama", "Afrodisias"], dogru: 1, aciklama: "Sardes (Sart) Antik Kenti, Bin Tepe Lidya Tümülüsleri ile birlikte 2025'te UNESCO Dünya Mirası Listesi'ne alınmış ve Türkiye'nin listedeki alan sayısı 22'ye ulaşmıştır. Sardes, Lidyalıların başkenti olup tarihte ilk madeni paranın basıldığı yer olarak bilinir. Diğer antik kentler de listede ya da geçici listededir ama 2025 eklemesi Sardes'tir." },
{ id: "gun-tufan-009", konu: "Bilim ve Teknoloji", soru: "2025 Nobel Fizik Ödülü, aşağıdaki alanların hangisindeki keşiflere verilmiştir?", secenekler: ["Kara deliklerin doğrudan gözlemlenmesi", "Genetik düzenleme (CRISPR) tekniği", "Elektrik devrelerinde makroskobik kuantum tünelleme", "Yapay zekâ öğrenme algoritmaları", "Higgs bozonunun keşfi"], dogru: 2, aciklama: "2025 Nobel Fizik Ödülü, bir elektrik devresinde makroskobik kuantum mekaniksel tünelleme ve enerjinin nicelenmesi olaylarının keşfine verilmiştir. Bu çalışma, kuantum mekaniğinin çok küçük parçacıklar dışında, gözle görülebilir ölçekli sistemlerde de gözlemlenebileceğini göstermesi bakımından önemlidir." },
{ id: "gun-tufan-010", konu: "Spor", soru: "2024 Avrupa Futbol Şampiyonası'nı (EURO 2024) kazanan ülke aşağıdakilerden hangisidir?", secenekler: ["İngiltere", "Fransa", "Almanya", "İspanya", "İtalya"], dogru: 3, aciklama: "EURO 2024 finalinde İspanya, İngiltere'yi 2-1 yenerek şampiyon olmuştur (final Almanya'nın başkenti Berlin'de oynanmıştır). İspanya, turnuvayı oynadığı yedi maçın tümünü kazanarak tamamlamış ve rekor sayılan dördüncü Avrupa şampiyonluğuna ulaşmıştır." },
{ id: "gun-tufan-011", konu: "Kültür-Sanat", soru: "2025 Nobel Edebiyat Ödülü aşağıdaki yazarlardan hangisine verilmiştir?", secenekler: ["Jon Fosse", "Annie Ernaux", "Han Kang", "Abdulrazak Gurnah", "László Krasznahorkai"], dogru: 4, aciklama: "2025 Nobel Edebiyat Ödülü, Macar yazar László Krasznahorkai'ye verilmiştir. Diğer seçeneklerdeki isimler önceki yıllarda bu ödülü kazanan yazarlardır (örneğin Jon Fosse 2023, Han Kang 2024); dolayısıyla 2025'in sahibi Krasznahorkai'dir." },
{ id: "gun-tufan-012", konu: "Ödüller", soru: "2025 Nobel Kimya Ödülü, aşağıdaki alanların hangisindeki gelişmelere verilmiştir?", secenekler: ["Metal-organik çerçevelerin (MOF) geliştirilmesi", "mRNA aşı teknolojisi", "Plastiklerin geri dönüşümü", "Yapay fotosentez", "Nükleer füzyon reaktörleri"], dogru: 0, aciklama: "2025 Nobel Kimya Ödülü, metal-organik çerçevelerin (MOF) geliştirilmesine verilmiştir. MOF'lar, çok gözenekli yapıları sayesinde gaz depolama, sudan içme suyu elde etme ve zararlı maddeleri süzme gibi alanlarda kullanılabilen yeni nesil malzemelerdir." }
);
