window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["vatandaslik"] = window.KPSS_BANK["vatandaslik"] || []).push(
{ id: "vat-tufan-010", konu: "Hukukun Temel Kavramları", soru: "Aşağıdakilerden hangisi kamu hukuku dallarından biri DEĞİLDİR?", secenekler: ["Borçlar Hukuku", "Anayasa Hukuku", "Ceza Hukuku", "İdare Hukuku", "Vergi Hukuku"], dogru: 0, aciklama: "Kamu hukuku, devletin taraf olduğu (devlet-birey veya devlet-devlet) ilişkileri düzenler; anayasa, ceza, idare ve vergi hukuku bu gruptadır. Borçlar Hukuku ise kişiler arasındaki ilişkileri düzenleyen bir özel hukuk dalıdır; bu yüzden kamu hukuku dalı değildir." },
{ id: "vat-tufan-011", konu: "Anayasa ve Genel Esaslar", soru: "1982 Anayasası'na göre Türkiye Cumhuriyeti'nin nitelikleri arasında aşağıdakilerden hangisi YER ALMAZ?", secenekler: ["Demokratik devlet", "Federal devlet", "Laik devlet", "Sosyal devlet", "Hukuk devleti"], dogru: 1, aciklama: "1982 Anayasası'nın 2. maddesine göre Türkiye Cumhuriyeti; insan haklarına saygılı, Atatürk milliyetçiliğine bağlı, demokratik, laik, sosyal bir hukuk devletidir. Türkiye üniter (tekçi) bir devlet olduğundan 'federal devlet' niteliği yer almaz; federalizm, eyaletlere dayalı bir devlet yapısıdır." },
{ id: "vat-tufan-012", konu: "Anayasa ve Genel Esaslar", soru: "1982 Anayasası'na göre egemenlik kayıtsız şartsız aşağıdakilerden hangisine aittir?", secenekler: ["Cumhurbaşkanı'na", "TBMM'ye", "Millete", "Hükûmete", "Yargı organlarına"], dogru: 2, aciklama: "Anayasa'ya göre 'Egemenlik kayıtsız şartsız Milletindir.' Millet, bu egemenliği Anayasa'nın koyduğu esaslara göre yetkili organlar (yasama, yürütme, yargı) eliyle kullanır. Hiçbir kişi veya organ, kaynağını Anayasa'dan almayan bir devlet yetkisi kullanamaz." },
{ id: "vat-tufan-013", konu: "Temel Hak ve Ödevler", soru: "Aşağıdakilerden hangisi sosyal ve ekonomik haklardan biridir?", secenekler: ["Konut dokunulmazlığı", "Kişi özgürlüğü ve güvenliği", "Düşünceyi açıklama özgürlüğü", "Eğitim ve öğrenim hakkı", "Seçme ve seçilme hakkı"], dogru: 3, aciklama: "Sosyal ve ekonomik haklar, devletten olumlu bir edim (hizmet) beklenen haklardır; eğitim, sağlık, sosyal güvenlik ve çalışma hakkı bu gruptadır. Konut dokunulmazlığı ve kişi özgürlüğü kişisel (koruyucu) haklar, seçme-seçilme ise siyasi haklardır." },
{ id: "vat-tufan-014", konu: "Temel Hak ve Ödevler", soru: "Aşağıdakilerden hangisi Anayasa'ya göre vatandaşın temel ödevlerinden biridir?", secenekler: ["Dilekçe vermek", "Seçme ve seçilmek", "Konut dokunulmazlığından yararlanmak", "Özel hayatının gizliliğini istemek", "Vergi ödemek"], dogru: 4, aciklama: "Anayasa'da düzenlenen temel vatandaşlık ödevleri; vergi verme, askerlik yapma ve kanunlara uymadır. Vergi ödemek, herkesin mali gücüne göre kamu giderlerine katılmasını sağlayan bir ödevdir. Dilekçe, seçme-seçilme, konut dokunulmazlığı ve özel hayatın gizliliği ise ödev değil haktır." },
{ id: "vat-tufan-015", konu: "Yasama", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde aşağıdakilerden hangisi TBMM'nin görevlerinden biri DEĞİLDİR?", secenekler: ["Bakanları atamak", "Kanun koymak, değiştirmek ve kaldırmak", "Bütçe kanununu görüşüp kabul etmek", "Savaş ilanına karar vermek", "Milletlerarası antlaşmaların onaylanmasını uygun bulmak"], dogru: 0, aciklama: "Bakanları atamak ve görevden almak, yürütmenin başı olan Cumhurbaşkanı'nın görevidir; TBMM'nin görevi değildir. TBMM'nin başlıca görevleri kanun yapmak, bütçeyi kabul etmek, savaş ilanına karar vermek ve uluslararası antlaşmaların onaylanmasını uygun bulmaktır." },
{ id: "vat-tufan-016", konu: "Yürütme", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde Cumhurbaşkanı seçilebilmek için aşağıdaki şartlardan hangisi gereklidir?", secenekler: ["En az 30 yaşını doldurmuş olmak", "40 yaşını doldurmuş ve yükseköğrenim yapmış olmak", "En az iki dönem milletvekilliği yapmış olmak", "En az 45 yaşında olmak", "Daha önce hâkimlik görevinde bulunmuş olmak"], dogru: 1, aciklama: "Cumhurbaşkanı seçilebilmek için; 40 yaşını doldurmuş, yükseköğrenim yapmış ve milletvekili seçilme yeterliliğine sahip Türk vatandaşı olmak gerekir. Cumhurbaşkanı halk tarafından beş yıllığına seçilir ve bir kişi en fazla iki dönem bu görevi yürütebilir." },
{ id: "vat-tufan-017", konu: "Yargı ve İdare", soru: "İdare mahkemelerinin verdiği kararların incelendiği, idari yargının en üst organı olan yüksek mahkeme aşağıdakilerden hangisidir?", secenekler: ["Yargıtay", "Anayasa Mahkemesi", "Danıştay", "Sayıştay", "Uyuşmazlık Mahkemesi"], dogru: 2, aciklama: "Danıştay, idari yargının en üst mahkemesidir; idare mahkemelerinin kararlarını inceler ve idari uyuşmazlıklarda son kararı verir. Yargıtay adli yargının (hukuk ve ceza davaları) üst mahkemesi, Sayıştay ise kamu kurumlarının mali denetimini yapan yüksek mahkemedir." },
{ id: "vat-tufan-018", konu: "Yargı ve İdare", soru: "1982 Anayasası'na göre yargı ile ilgili aşağıdakilerden hangisi doğrudur?", secenekler: ["Hâkimler yürütme organının emri altında görev yapar.", "Mahkeme kararları Cumhurbaşkanı'nın onayıyla kesinleşir.", "Yargı yetkisi doğrudan TBMM tarafından kullanılır.", "Mahkemeler bağımsızdır ve hâkimler teminat altındadır.", "Hâkimler beş yıllığına halk tarafından seçilir."], dogru: 3, aciklama: "Anayasa'ya göre yargı yetkisi, bağımsız ve tarafsız mahkemelerce kullanılır; hâkimler görevlerinde bağımsızdır ve hâkimlik teminatına sahiptir (kendi istekleri olmadıkça azledilemez, emekliye ayrılamaz). Hâkimler kararlarını Anayasa'ya, kanuna ve vicdani kanaatlerine göre verir; hiçbir organ mahkemelere emir veremez." }
);
