window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["vatandaslik"] = window.KPSS_BANK["vatandaslik"] || []).push(
{ id: "vat-tufan-019", konu: "Hukukun Temel Kavramları", soru: "Türk hukukunda normlar hiyerarşisinin (kurallar sıralamasının) en üstünde aşağıdakilerden hangisi yer alır?", secenekler: ["Anayasa", "Kanun", "Cumhurbaşkanlığı kararnamesi", "Yönetmelik", "Genelge"], dogru: 0, aciklama: "Normlar hiyerarşisi, hukuk kurallarının alttan üste doğru sıralanmasıdır ve alt sıradaki kural üst sıradakine aykırı olamaz. Bu sıralamanın en üstünde Anayasa bulunur; onu kanunlar ve Cumhurbaşkanlığı kararnameleri, ardından yönetmelikler izler. Anayasa'nın üstünlüğü ilkesi budur." },
{ id: "vat-tufan-020", konu: "Anayasa ve Genel Esaslar", soru: "1982 Anayasası'na göre yasama yetkisi kime aittir ve bu yetki devredilebilir mi?", secenekler: ["Cumhurbaşkanına aittir ve devredilebilir.", "Türk Milleti adına TBMM'ye aittir ve devredilemez.", "Bakanlar Kuruluna aittir ve devredilebilir.", "Yargı organlarına aittir ve devredilemez.", "Doğrudan halka aittir ve devredilebilir."], dogru: 1, aciklama: "Anayasa'ya göre yasama yetkisi (kanun koyma, değiştirme, kaldırma) Türk Milleti adına Türkiye Büyük Millet Meclisi'nindir ve bu yetki devredilemez. Yasama yetkisinin devredilemez olması, egemenliğin millet adına yalnızca TBMM tarafından kullanılmasını güvence altına alır." },
{ id: "vat-tufan-021", konu: "Anayasa ve Genel Esaslar", soru: "1982 Anayasası'na göre Anayasa hükümleri kimleri bağlar?", secenekler: ["Yalnızca yasama organını", "Yalnızca yürütme organını", "Yasama, yürütme ve yargı organları ile idare makamlarını ve herkesi", "Yalnızca kamu görevlilerini", "Yalnızca Cumhurbaşkanını"], dogru: 2, aciklama: "Anayasa, en üstün ve bağlayıcı hukuk kuralıdır. Anayasa hükümleri; yasama, yürütme ve yargı organlarını, idare makamlarını ve diğer kuruluş ve kişileri bağlayan temel hukuk kurallarıdır. Yani devletin bütün organları ve herkes Anayasa'ya uymak zorundadır." },
{ id: "vat-tufan-022", konu: "Temel Hak ve Ödevler", soru: "1982 Anayasası'na göre temel hak ve hürriyetlerin sınırlandırılmasıyla ilgili aşağıdakilerden hangisi doğrudur?", secenekler: ["Cumhurbaşkanı kararnamesiyle serbestçe sınırlanabilir.", "Hiçbir durumda sınırlandırılamaz.", "Valilik kararıyla sınırlanabilir.", "Ancak kanunla, Anayasanın sözüne ve ruhuna uygun ve ölçülülük ilkesine bağlı olarak sınırlanabilir.", "Sınırlandırmada hakkın özüne dokunulabilir."], dogru: 3, aciklama: "Temel hak ve hürriyetler yalnızca kanunla, Anayasa'da belirtilen sebeplere bağlı olarak ve ölçülülük ilkesine uygun biçimde sınırlanabilir. Bu sınırlama, hakkın özüne dokunamaz ve Anayasanın sözüne ve ruhuna aykırı olamaz. Ayrıca temel haklar, kararnameyle düzenlenemez." },
{ id: "vat-tufan-023", konu: "Temel Hak ve Ödevler", soru: "Aşağıdakilerden hangisi siyasi haklar ve ödevlerden biridir?", secenekler: ["Konut dokunulmazlığı", "Sağlık hakkı", "Çalışma hakkı", "Özel hayatın gizliliği", "Seçme, seçilme ve siyasi parti kurma hakkı"], dogru: 4, aciklama: "Siyasi haklar, vatandaşın devlet yönetimine katılmasını sağlayan haklardır; seçme-seçilme, siyasi parti kurma, kamu hizmetine girme ve dilekçe hakkı bu gruptadır. Konut dokunulmazlığı ve özel hayatın gizliliği kişisel haklar; sağlık ve çalışma ise sosyal-ekonomik haklardır." },
{ id: "vat-tufan-024", konu: "Yasama", soru: "Milletvekillerinin, Meclis çalışmalarındaki oy, düşünce ve söz açıklamalarından dolayı hukuki veya cezai olarak sorumlu tutulamamasına ne ad verilir?", secenekler: ["Yasama sorumsuzluğu", "Yasama dokunulmazlığı", "Yargı bağımsızlığı", "Siyasi sorumluluk", "Cezai muafiyet"], dogru: 0, aciklama: "Yasama sorumsuzluğu (kürsü dokunulmazlığı), milletvekilinin Meclisteki oy, söz ve düşüncelerinden dolayı sorumlu tutulamamasıdır; kalıcıdır ve görev bittikten sonra da devam eder. Yasama dokunulmazlığı ise vekilin görev süresince tutuklanıp yargılanmasını engelleyen, geçici ve kaldırılabilir bir korumadır." },
{ id: "vat-tufan-025", konu: "Yürütme", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde olağanüstü hâl (OHAL) ile ilgili aşağıdakilerden hangisi doğrudur?", secenekler: ["OHAL yalnızca TBMM tarafından ilan edilir.", "OHAL'i Cumhurbaşkanı ilan eder; karar aynı gün Resmî Gazete'de yayımlanır ve TBMM'nin onayına sunulur.", "OHAL süresi 6 aydır ve hiçbir biçimde uzatılamaz.", "OHAL süresince hiçbir temel hak sınırlandırılamaz.", "OHAL ilanına Anayasa Mahkemesi karar verir."], dogru: 1, aciklama: "2017 değişikliğiyle gelen sisteme göre olağanüstü hâli Cumhurbaşkanı ilan eder; bu karar aynı gün Resmî Gazete'de yayımlanır ve aynı gün TBMM'nin onayına sunulur. TBMM, OHAL süresini değiştirebilir, uzatabilir veya olağanüstü hâli kaldırabilir." },
{ id: "vat-tufan-026", konu: "Yargı ve İdare", soru: "Hukuk ve ceza davalarına bakan mahkemelerin (adli yargının) verdiği kararların incelendiği, adli yargının en üst mahkemesi aşağıdakilerden hangisidir?", secenekler: ["Danıştay", "Sayıştay", "Yargıtay", "Anayasa Mahkemesi", "Uyuşmazlık Mahkemesi"], dogru: 2, aciklama: "Yargıtay, hukuk ve ceza mahkemelerinin (adli yargı) kararlarını son merci olarak inceleyen en üst mahkemedir. Danıştay idari yargının, Sayıştay ise kamu kurumlarının mali denetiminin üst organıdır; Uyuşmazlık Mahkemesi ise yargı kolları arasındaki görev ve hüküm uyuşmazlıklarını çözer." },
{ id: "vat-tufan-027", konu: "Yargı ve İdare", soru: "Türk yargı sisteminde aşağıdakilerden hangisi bir yargı kolu (türü) değildir?", secenekler: ["Adli yargı", "İdari yargı", "Anayasa yargısı", "Siyasi yargı", "Hesap (mali) yargısı"], dogru: 3, aciklama: "Türk yargı düzeni; anayasa yargısı, adli yargı, idari yargı ve hesap (mali) yargısı gibi kollardan oluşur. 'Siyasi yargı' diye bir yargı kolu bulunmadığından doğru cevap odur. Her yargı kolunun kendine özgü mahkemeleri ve üst denetim organı vardır." }
);
