window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["vatandaslik"] = window.KPSS_BANK["vatandaslik"] || []).push(
{ id: "vat-tufan-001", konu: "Hukukun Temel Kavramları", soru: "Bir hukuk kuralına uyulmaması durumunda, devlet gücüyle uygulanan zorlayıcı tepkiye (hapis, para cezası, tazminat gibi) ne ad verilir?", secenekler: ["Yaptırım", "Teamül", "İçtihat", "Örf", "Ahlak kuralı"], dogru: 0, aciklama: "Yaptırım, bir hukuk kuralının ihlali hâlinde devletin uyguladığı maddi ve zorlayıcı tepkidir; hukuk kurallarını ahlak veya görgü kurallarından ayıran temel özellik budur. İçtihat, mahkeme kararlarıyla oluşan hukuktur; örf ve teamül ise toplumda yerleşmiş uygulamalardır. Ahlak kurallarının yaptırımı manevidir (kınama gibi), maddi değildir." },
{ id: "vat-tufan-002", konu: "Anayasa ve Genel Esaslar", soru: "1982 Anayasası'na göre aşağıdakilerden hangisi değiştirilemez ve değiştirilmesi teklif edilemez ilkelerden biri DEĞİLDİR?", secenekler: ["Devlet şeklinin Cumhuriyet olması", "Devletin laik bir devlet olması", "Başkentin Ankara olması", "Resmî dilin Türkçe olması", "Ekonomik sistemin karma ekonomi olması"], dogru: 4, aciklama: "1982 Anayasası'nın ilk üç maddesi (devletin Cumhuriyet oluşu, Cumhuriyet'in nitelikleri -laiklik dâhil- ve devletin bütünlüğü, dili, başkenti, bayrağı, marşı) değiştirilemez ve değiştirilmesi teklif edilemez. Ekonomik sistemin karma ekonomi olması ise bu değiştirilemez ilkeler arasında yer almaz." },
{ id: "vat-tufan-003", konu: "Anayasa ve Genel Esaslar", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde, Cumhurbaşkanı'nın yürütme yetkisine ilişkin konularda çıkardığı düzenleyici işleme ne ad verilir?", secenekler: ["Kanun", "Cumhurbaşkanlığı kararnamesi", "Tüzük", "Kanun hükmünde kararname", "Genelge"], dogru: 1, aciklama: "2017 Anayasa değişikliğiyle gelen sistemde Cumhurbaşkanı, yürütmeye ilişkin konuları Cumhurbaşkanlığı kararnamesiyle düzenler; eski sistemdeki kanun hükmünde kararname (KHK) kaldırılmıştır. Ancak temel haklar, kişi hakları ve kanunla düzenlenmesi gereken konularda kararname çıkarılamaz; kararname kanuna aykırı olamaz." },
{ id: "vat-tufan-004", konu: "Temel Hak ve Ödevler", soru: "1982 Anayasası'nda temel hak ve hürriyetler; kişi hakları, sosyal-ekonomik haklar ve siyasi haklar olarak gruplandırılır. Buna göre aşağıdakilerden hangisi 'kişi hakları ve ödevleri' (koruyucu haklar) arasında yer alır?", secenekler: ["Seçme ve seçilme hakkı", "Eğitim ve öğrenim hakkı", "Konut dokunulmazlığı", "Dilekçe hakkı", "Sağlık hakkı"], dogru: 2, aciklama: "Kişi hakları, devletin bireyin özel alanına karışmamasını isteyen koruyucu (negatif statü) haklardır; konut dokunulmazlığı, özel hayatın gizliliği ve yaşama hakkı bu gruptadır. Seçme-seçilme ve dilekçe hakkı siyasi (katılma) haklar; eğitim ve sağlık ise sosyal-ekonomik (isteme) haklardır." },
{ id: "vat-tufan-005", konu: "Temel Hak ve Ödevler", soru: "1982 Anayasası'na göre, savaş, seferberlik ve olağanüstü hâllerde dahi dokunulamayan 'çekirdek haklar' arasında aşağıdakilerden hangisi yer alır?", secenekler: ["Kişinin yaşama hakkı ve maddi-manevi varlığının bütünlüğü", "Grev hakkı", "Toplantı ve gösteri yürüyüşü hakkı", "Yerleşme ve seyahat hürriyeti", "Sendika kurma hakkı"], dogru: 0, aciklama: "Olağanüstü dönemlerde birçok hak sınırlanabilir; ancak kişinin yaşama hakkı (meşru savunma hâli dışında), maddi-manevi varlığının bütünlüğü, din-vicdan hürriyeti, masumiyet karinesi ve suçların geriye yürümezliği gibi çekirdek haklara dokunulamaz. Grev, toplantı ve seyahat gibi haklar ise olağanüstü hâlde sınırlanabilir." },
{ id: "vat-tufan-006", konu: "Yasama", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde TBMM (yasama) ile ilgili aşağıdakilerden hangisi doğrudur?", secenekler: ["Milletvekili sayısı 550'dir.", "Milletvekili genel seçimleri 4 yılda bir yapılır.", "Milletvekili seçilme yaşı 25'tir.", "Milletvekili sayısı 600'dür ve seçimler 5 yılda bir yapılır.", "Kanun yapma yetkisi Cumhurbaşkanı'na aittir."], dogru: 3, aciklama: "2017 Anayasa değişikliğinden sonra TBMM 600 milletvekilinden oluşur ve genel seçimler 5 yılda bir yapılır. Aynı değişiklikle milletvekili seçilme yaşı 25'ten 18'e indirilmiştir. Yasama (kanun yapma) yetkisi Anayasa'ya göre yalnızca TBMM'ye aittir ve bu yetki devredilemez." },
{ id: "vat-tufan-007", konu: "Yürütme", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde Cumhurbaşkanı ile ilgili aşağıdakilerden hangisi yanlıştır?", secenekler: ["Halk tarafından beş yıllığına seçilir.", "Bir kişi en fazla iki dönem Cumhurbaşkanı seçilebilir.", "Hem devletin hem de yürütmenin başıdır.", "Cumhurbaşkanı yardımcılarını ve bakanları kendisi atar.", "Çıkardığı her kararnameyi TBMM'nin onayına sunmak zorundadır."], dogru: 4, aciklama: "Cumhurbaşkanlığı kararnameleri, yürürlüğe girmesi için TBMM'nin onayına sunulmak zorunda değildir; bu yüzden E yanlıştır. Ancak TBMM aynı konuda kanun çıkarırsa kararname hükümsüz kalır. Cumhurbaşkanı halk tarafından 5 yıllığına ve en çok iki dönem için seçilir; devletin ve yürütmenin başıdır, yardımcılarını ve bakanları kendisi atar." },
{ id: "vat-tufan-008", konu: "Yargı ve İdare", soru: "2017 Anayasa değişikliği sonrasındaki düzenlemeye göre Hâkimler ve Savcılar Kurulu (HSK) kaç üyeden oluşur?", secenekler: ["7", "11", "13", "15", "22"], dogru: 2, aciklama: "HSK 13 üyeden oluşur: Kurulun başkanı Adalet Bakanı'dır ve Adalet Bakanı Yardımcısı da doğal üyedir; üyelerin 4'ünü Cumhurbaşkanı, 7'sini TBMM seçer. 2017 öncesinde kurul (HSYK) 22 üyeliydi; değişiklikle üye sayısı ve seçim usulü değişmiştir." },
{ id: "vat-tufan-009", konu: "Yargı ve İdare", soru: "Anayasa Mahkemesi ile ilgili aşağıdakilerden hangisi doğrudur?", secenekler: ["Üyeleri ömür boyu görev yapar.", "15 üyeden oluşur ve üyelerinin çoğunu Cumhurbaşkanı seçer.", "Bütün üyeleri TBMM tarafından seçilir.", "Bireysel başvuruları incelemez.", "17 üyeden oluşur."], dogru: 1, aciklama: "Anayasa Mahkemesi 15 üyeden oluşur; bunların 12'sini Cumhurbaşkanı, 3'ünü TBMM seçer, dolayısıyla üyelerin çoğunu Cumhurbaşkanı belirler. Üyeler 12 yıllığına ve bir kez seçilir, ömür boyu görev yapmaz. Mahkeme, temel hakları ihlal edilenlerin yaptığı bireysel başvuruları da inceler." }
);
